//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.16 at 12:53:11 AM CEST 
//


package es.um.arso.pelicula;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the es.um.arso.pelicula package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: es.um.arso.pelicula
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CriticaPrensa }
     * 
     */
    public CriticaPrensa createCriticaPrensa() {
        return new CriticaPrensa();
    }

    /**
     * Create an instance of {@link PeliculaAmazon }
     * 
     */
    public PeliculaAmazon createPeliculaAmazon() {
        return new PeliculaAmazon();
    }

    /**
     * Create an instance of {@link CriticaUsuario }
     * 
     */
    public CriticaUsuario createCriticaUsuario() {
        return new CriticaUsuario();
    }

    /**
     * Create an instance of {@link CriticasUsuario }
     * 
     */
    public CriticasUsuario createCriticasUsuario() {
        return new CriticasUsuario();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link LibroAmazon }
     * 
     */
    public LibroAmazon createLibroAmazon() {
        return new LibroAmazon();
    }

    /**
     * Create an instance of {@link DescripcionPeliculaAmazon }
     * 
     */
    public DescripcionPeliculaAmazon createDescripcionPeliculaAmazon() {
        return new DescripcionPeliculaAmazon();
    }

    /**
     * Create an instance of {@link Languages }
     * 
     */
    public Languages createLanguages() {
        return new Languages();
    }

    /**
     * Create an instance of {@link DescripcionPelicula }
     * 
     */
    public DescripcionPelicula createDescripcionPelicula() {
        return new DescripcionPelicula();
    }

    /**
     * Create an instance of {@link Pelicula }
     * 
     */
    public Pelicula createPelicula() {
        return new Pelicula();
    }

    /**
     * Create an instance of {@link DescripcionLibroAmazon }
     * 
     */
    public DescripcionLibroAmazon createDescripcionLibroAmazon() {
        return new DescripcionLibroAmazon();
    }

    /**
     * Create an instance of {@link CriticasPrensa }
     * 
     */
    public CriticasPrensa createCriticasPrensa() {
        return new CriticasPrensa();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

}
