
package es.um.arso.cliente.tipos;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "PeliculaException", targetNamespace = "http://server.arso.um.es/")
public class PeliculaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PeliculaException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public PeliculaException_Exception(String message, PeliculaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public PeliculaException_Exception(String message, PeliculaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: es.um.arso.cliente.tipos.PeliculaException
     */
    public PeliculaException getFaultInfo() {
        return faultInfo;
    }

}
